# def members_label(self, board_id):
#     members = TrelloManager(self.trello_username).get_board_members(board_id)
#     data = []
#     cur = connection.cursor(cursor_factory=RealDictCursor)
#     sql = 'CREATE TABLE if not exists members(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,' \
#           'full_name varchar(100)not null,trello_username varchar(100) unique not null,' \
#           'trello_id varchar(80)unique not null )  '
#     cur.execute(sql)
#     connection.commit()
#     cur.close()
#     for i in members:
#         curr = connection.cursor()
#         sql = 'insert into members(full_name,trello_username,trello_id)values (%s,%s,%s)' \
#               'on conflict (trello_id) do update set full_name = excluded.full_name'
#         curr.execute(sql, (i.get('fullName'), i.get('username'), i.get('id')))
#         connection.commit()
#         with connection.cursor() as m:
#             m.execute(f"select full_name,trello_id from members where trello_username ='{i['username']}'")
#             s = m.fetchall()
#             for row in s:
#                 data.append({
#                     'fullName': row[0],
#                     'id': row[1]
#                 })
#     cur = connection.cursor(cursor_factory=RealDictCursor)
#     sql = 'CREATE TABLE if not exists members_one(id int,cards_id int unique ,memberes_id int unique ,' \
#           'foreign key(cards_id)references cards(id),foreign key (memberes_id)references members(id))'
#     cur.execute(sql)
#     connection.commit()
#     cur.close()
#     con = connection.cursor()
#     sql = 'insert into members_one(cards_id)values (%s) on conflict (cards_id)do nothing '
#     con.execute('select id from cards')
#     name = con.fetchall()
#     for j in name:
#         con.execute(sql, (j))
#         connection.commit()
#     sql = 'insert into members_one(memberes_id)values (%s) on conflict (memberes_id)do update set memberes_id=excluded.memberes_id'
#     con.execute('select id from members')
#     name = con.fetchall()
#     for i in name:
#         con.execute(sql, (i))
#         connection.commit()
#     con.close()
#     return data
#
#
# def labels_trello(self, board_id):
#     label = TrelloManager(self.trello_username).get_label(board_id)
#
#     data = []
#     cur = connection.cursor(cursor_factory=RealDictCursor)
#     sql = "CREATE TABLE if not exists labels(id int generated by default as identity primary key," \
#           "label_name varchar(60)not null ,color varchar(50)," \
#           "label_id varchar(80) unique not null,board_id int references boards(id),board_d varchar(60)not null)"
#     cur.execute(sql)
#     connection.commit()
#     cur.close()
#     for i in label:
#         curr = connection.cursor()
#         sql = 'insert into labels(label_name, color, label_id,board_id,board_d)values (%s,%s,%s,%s,%s)on conflict (label_id)do update set label_name = excluded.label_name'
#         curr.execute(f"select id from boards where trello_id='{board_id}'")
#         name = curr.fetchall()
#         curr.execute(sql, (i.get('name'), i.get('color'), i.get('id'), name[0][0], i.get('idBoard')))
#         connection.commit()
#         curr.close()
#     with connection.cursor() as l:
#         l.execute(f"select label_name,label_id from labels where board_d ='{board_id}'")
#         s = l.fetchall()
#         for i in s:
#             data.append({
#                 'name': i[0],
#                 'id': i[1]
#
#             })
#     cards = connection.cursor()
#
#     con = 'CREATE TABLE if not exists cards_label(id int, card_id int unique ,label_id int unique ,' \
#           'foreign key (card_id)references cards(id),foreign key (label_id)references labels(id))'
#     cards.execute(con)
#     connection.commit()
#     cards.close()
#     con1 = connection.cursor()
#     card = 'insert into cards_label(card_id)values (%s) on conflict (card_id)do nothing '
#     con1.execute('select id from cards')
#     name = con1.fetchall()
#     for j in name:
#         con1.execute(card, (j))
#         connection.commit()
#     sql = 'insert into cards_label(label_id)values (%s) on conflict (label_id)do nothing '
#     con1.execute('select id from labels')
#     name = con1.fetchall()
#     for i in name:
#         con1.execute(sql, (i))
#         connection.commit()
#     con1.close()
#
#     return
from Trello.trello import TrelloManager

# s=TrelloManager('otabekismailov3'). get_cards_on_a_list('64039b9d36372f1c57dcd97f')
# print(s)
a = [{'id': '63ea227728ee0b875a66f2f5', 'fullName': 'otabek ismailov', 'username': 'otabekismailov3'}]
s = TrelloManager('otabekismailov3').get_cards_on_a_list('6404dc277428ce45a12d3102')
print(s)

# cur.execute(query.quary.GET_MEMBERS_ID, (member_id,))
# _id = cur.fetchall()
# print(_id[0].get("id") )
# connection.commit()


b = [{'id': '64039b9d36372f1c57dcd97f',
      'nodeId': 'ari:cloud:trello::board/workspace/63ea2305039a525e80a5a455/64039b9d36372f1c57dcd97f', 'name': '1212',
      'desc': '', 'descData': None, 'closed': False, 'dateClosed': None, 'idOrganization': '63ea2305039a525e80a5a455',
      'idEnterprise': None, 'limits': {
        'attachments': {'perBoard': {'status': 'ok', 'disableAt': 36000, 'warnAt': 28800},
                        'perCard': {'status': 'ok', 'disableAt': 1000, 'warnAt': 800}},
        'boards': {'totalMembersPerBoard': {'status': 'ok', 'disableAt': 1600, 'warnAt': 1280},
                   'totalAccessRequestsPerBoard': {'status': 'ok', 'disableAt': 4000, 'warnAt': 3200}},
        'cards': {'openPerBoard': {'status': 'ok', 'disableAt': 5000, 'warnAt': 4000},
                  'openPerList': {'status': 'ok', 'disableAt': 5000, 'warnAt': 4000},
                  'totalPerBoard': {'status': 'ok', 'disableAt': 2000000, 'warnAt': 1600000},
                  'totalPerList': {'status': 'ok', 'disableAt': 1000000, 'warnAt': 800000}},
        'checklists': {'perBoard': {'status': 'ok', 'disableAt': 1800000, 'warnAt': 1440000},
                       'perCard': {'status': 'ok', 'disableAt': 500, 'warnAt': 400}},
        'checkItems': {'perChecklist': {'status': 'ok', 'disableAt': 200, 'warnAt': 160}},
        'customFields': {'perBoard': {'status': 'ok', 'disableAt': 50, 'warnAt': 40}},
        'customFieldOptions': {'perField': {'status': 'ok', 'disableAt': 50, 'warnAt': 40}},
        'labels': {'perBoard': {'status': 'ok', 'disableAt': 1000, 'warnAt': 800}},
        'lists': {'openPerBoard': {'status': 'ok', 'disableAt': 500, 'warnAt': 400},
                  'totalPerBoard': {'status': 'ok', 'disableAt': 3000, 'warnAt': 2400}},
        'stickers': {'perCard': {'status': 'ok', 'disableAt': 70, 'warnAt': 56}},
        'reactions': {'perAction': {'status': 'ok', 'disableAt': 900, 'warnAt': 720},
                      'uniquePerAction': {'status': 'ok', 'disableAt': 17, 'warnAt': 14}}}, 'pinned': False,
      'starred': False, 'url': 'https://trello.com/b/V91qOKfj/1212',
      'prefs': {'permissionLevel': 'org', 'hideVotes': False, 'voting': 'disabled', 'comments': 'members',
                'invitations': 'members', 'selfJoin': True, 'cardCovers': True, 'isTemplate': False,
                'cardAging': 'regular', 'calendarFeedEnabled': False, 'hiddenPluginBoardButtons': [], 'switcherViews': [
              {'viewType': 'Board', 'enabled': True, '_id': '64039b9d36372f1c57dcd980', 'typeName': 'SwitcherViews',
               'id': '64039b9d36372f1c57dcd980'},
              {'viewType': 'Table', 'enabled': True, '_id': '64039b9d36372f1c57dcd981', 'typeName': 'SwitcherViews',
               'id': '64039b9d36372f1c57dcd981'},
              {'viewType': 'Calendar', 'enabled': False, '_id': '64039b9d36372f1c57dcd982', 'typeName': 'SwitcherViews',
               'id': '64039b9d36372f1c57dcd982'},
              {'viewType': 'Dashboard', 'enabled': False, '_id': '64039b9d36372f1c57dcd983',
               'typeName': 'SwitcherViews', 'id': '64039b9d36372f1c57dcd983'},
              {'viewType': 'Timeline', 'enabled': False, '_id': '64039b9d36372f1c57dcd984', 'typeName': 'SwitcherViews',
               'id': '64039b9d36372f1c57dcd984'},
              {'viewType': 'Map', 'enabled': False, '_id': '64039b9d36372f1c57dcd985', 'typeName': 'SwitcherViews',
               'id': '64039b9d36372f1c57dcd985'}], 'background': '6403902ff719ff7c24bbb152', 'backgroundColor': None,
                'backgroundImage': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/original/c0954cbaad90c00e69c910ceb9cf9fc3/photo-1677647598949-6b6689bd53f6',
                'backgroundImageScaled': [{'width': 140, 'height': 88,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/140x88/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 256, 'height': 160,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/256x160/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 480, 'height': 300,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/480x300/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 960, 'height': 601,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/960x601/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 1024, 'height': 641,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1024x641/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 1280, 'height': 801,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1280x801/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 1920, 'height': 1202,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1920x1202/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 2048, 'height': 1282,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/2048x1282/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 2557, 'height': 1600,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/2557x1600/329171fc4c1cde901a6dd90849d2114e/photo-1677647598949-6b6689bd53f6.jpg'},
                                          {'width': 2560, 'height': 1602,
                                           'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/original/c0954cbaad90c00e69c910ceb9cf9fc3/photo-1677647598949-6b6689bd53f6'}],
                'backgroundTile': False, 'backgroundBrightness': 'dark', 'backgroundBottomColor': '#0e161f',
                'backgroundTopColor': '#24292c', 'canBePublic': True, 'canBeEnterprise': True, 'canBeOrg': True,
                'canBePrivate': True, 'canInvite': True}, 'shortLink': 'V91qOKfj', 'subscribed': False,
      'labelNames': {'green': 'erroo', 'yellow': 'eror', 'orange': 'qqqqwe', 'red': 'fbfbgbg', 'purple': 'ng ggrfefe',
                     'blue': '3232323', 'sky': 'bot', 'lime': '', 'pink': '', 'black': '', 'green_dark': '',
                     'yellow_dark': '', 'orange_dark': '', 'red_dark': '', 'purple_dark': '', 'blue_dark': '',
                     'sky_dark': '', 'lime_dark': '', 'pink_dark': '', 'black_dark': '', 'green_light': '',
                     'yellow_light': '', 'orange_light': '', 'red_light': '', 'purple_light': '', 'blue_light': '',
                     'sky_light': '', 'lime_light': '', 'pink_light': '', 'black_light': ''}, 'powerUps': [],
      'dateLastActivity': '2023-03-10T00:38:15.166Z', 'dateLastView': '2023-03-11T12:34:29.115Z',
      'shortUrl': 'https://trello.com/b/V91qOKfj', 'idTags': [], 'datePluginDisable': None, 'creationMethod': None,
      'ixUpdate': '47', 'templateGallery': None, 'enterpriseOwned': False, 'idBoardSource': None,
      'premiumFeatures': ['additionalBoardBackgrounds', 'additionalStickers', 'customBoardBackgrounds', 'customEmoji',
                          'customStickers', 'plugins'], 'idMemberCreator': '63ea227728ee0b875a66f2f5', 'memberships': [
        {'idMember': '63ea227728ee0b875a66f2f5', 'memberType': 'admin', 'unconfirmed': False, 'deactivated': False,
         'id': '64039b9d36372f1c57dcd987'}]}, {'id': '63ea22a4dd3aa382a077fb9f',
                                               'nodeId': 'ari:cloud:trello::board/workspace/63ea22a4dd3aa382a077fb86/63ea22a4dd3aa382a077fb9f',
                                               'name': 'P10', 'desc': '', 'descData': None, 'closed': False,
                                               'dateClosed': None, 'idOrganization': '63ea22a4dd3aa382a077fb86',
                                               'idEnterprise': None, 'limits': {
        'attachments': {'perBoard': {'status': 'ok', 'disableAt': 36000, 'warnAt': 28800},
                        'perCard': {'status': 'ok', 'disableAt': 1000, 'warnAt': 800}},
        'boards': {'totalMembersPerBoard': {'status': 'ok', 'disableAt': 1600, 'warnAt': 1280},
                   'totalAccessRequestsPerBoard': {'status': 'ok', 'disableAt': 4000, 'warnAt': 3200}},
        'cards': {'openPerBoard': {'status': 'ok', 'disableAt': 5000, 'warnAt': 4000},
                  'openPerList': {'status': 'ok', 'disableAt': 5000, 'warnAt': 4000},
                  'totalPerBoard': {'status': 'ok', 'disableAt': 2000000, 'warnAt': 1600000},
                  'totalPerList': {'status': 'ok', 'disableAt': 1000000, 'warnAt': 800000}},
        'checklists': {'perBoard': {'status': 'ok', 'disableAt': 1800000, 'warnAt': 1440000},
                       'perCard': {'status': 'ok', 'disableAt': 500, 'warnAt': 400}},
        'checkItems': {'perChecklist': {'status': 'ok', 'disableAt': 200, 'warnAt': 160}},
        'customFields': {'perBoard': {'status': 'ok', 'disableAt': 50, 'warnAt': 40}},
        'customFieldOptions': {'perField': {'status': 'ok', 'disableAt': 50, 'warnAt': 40}},
        'labels': {'perBoard': {'status': 'ok', 'disableAt': 1000, 'warnAt': 800}},
        'lists': {'openPerBoard': {'status': 'ok', 'disableAt': 500, 'warnAt': 400},
                  'totalPerBoard': {'status': 'ok', 'disableAt': 3000, 'warnAt': 2400}},
        'stickers': {'perCard': {'status': 'ok', 'disableAt': 70, 'warnAt': 56}},
        'reactions': {'perAction': {'status': 'ok', 'disableAt': 900, 'warnAt': 720},
                      'uniquePerAction': {'status': 'ok', 'disableAt': 17, 'warnAt': 14}}}, 'pinned': False,
                                               'starred': False, 'url': 'https://trello.com/b/rAWuxf08/p10',
                                               'prefs': {'permissionLevel': 'private', 'hideVotes': False,
                                                         'voting': 'disabled', 'comments': 'members',
                                                         'invitations': 'members', 'selfJoin': False,
                                                         'cardCovers': True, 'isTemplate': False,
                                                         'cardAging': 'regular', 'calendarFeedEnabled': False,
                                                         'hiddenPluginBoardButtons': [], 'switcherViews': [
                                                       {'viewType': 'Board', 'enabled': True,
                                                        '_id': '63ea22a4dd3aa382a077fba0', 'typeName': 'SwitcherViews',
                                                        'id': '63ea22a4dd3aa382a077fba0'},
                                                       {'viewType': 'Table', 'enabled': True,
                                                        '_id': '63ea22a4dd3aa382a077fba1', 'typeName': 'SwitcherViews',
                                                        'id': '63ea22a4dd3aa382a077fba1'},
                                                       {'viewType': 'Calendar', 'enabled': False,
                                                        '_id': '63ea22a4dd3aa382a077fba2', 'typeName': 'SwitcherViews',
                                                        'id': '63ea22a4dd3aa382a077fba2'},
                                                       {'viewType': 'Dashboard', 'enabled': False,
                                                        '_id': '63ea22a4dd3aa382a077fba3', 'typeName': 'SwitcherViews',
                                                        'id': '63ea22a4dd3aa382a077fba3'},
                                                       {'viewType': 'Timeline', 'enabled': False,
                                                        '_id': '63ea22a4dd3aa382a077fba4', 'typeName': 'SwitcherViews',
                                                        'id': '63ea22a4dd3aa382a077fba4'},
                                                       {'viewType': 'Map', 'enabled': False,
                                                        '_id': '63ea22a4dd3aa382a077fba5', 'typeName': 'SwitcherViews',
                                                        'id': '63ea22a4dd3aa382a077fba5'}],
                                                         'background': '63ea14a489b77288b9d89851',
                                                         'backgroundColor': None,
                                                         'backgroundImage': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/original/15fef5e25c20ace59280bfd8e925e0e7/photo-1675458349418-b6e8215f1d6b',
                                                         'backgroundImageScaled': [{'width': 67, 'height': 100,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/67x100/dd4a866597818404cfebcd11cccc425b/photo-1675458349418-b6e8215f1d6b.jpg'},
                                                                                   {'width': 128, 'height': 192,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/128x192/dd4a866597818404cfebcd11cccc425b/photo-1675458349418-b6e8215f1d6b.jpg'},
                                                                                   {'width': 320, 'height': 480,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/320x480/dd4a866597818404cfebcd11cccc425b/photo-1675458349418-b6e8215f1d6b.jpg'},
                                                                                   {'width': 640, 'height': 960,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/640x960/dd4a866597818404cfebcd11cccc425b/photo-1675458349418-b6e8215f1d6b.jpg'},
                                                                                   {'width': 683, 'height': 1024,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/683x1024/dd4a866597818404cfebcd11cccc425b/photo-1675458349418-b6e8215f1d6b.jpg'},
                                                                                   {'width': 853, 'height': 1280,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/853x1280/dd4a866597818404cfebcd11cccc425b/photo-1675458349418-b6e8215f1d6b.jpg'},
                                                                                   {'width': 1066, 'height': 1600,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1066x1600/dd4a866597818404cfebcd11cccc425b/photo-1675458349418-b6e8215f1d6b.jpg'},
                                                                                   {'width': 1280, 'height': 1920,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1280x1920/dd4a866597818404cfebcd11cccc425b/photo-1675458349418-b6e8215f1d6b.jpg'},
                                                                                   {'width': 1365, 'height': 2048,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/original/15fef5e25c20ace59280bfd8e925e0e7/photo-1675458349418-b6e8215f1d6b'}],
                                                         'backgroundTile': False, 'backgroundBrightness': 'dark',
                                                         'backgroundBottomColor': '#868385',
                                                         'backgroundTopColor': '#aab3b9', 'canBePublic': True,
                                                         'canBeEnterprise': True, 'canBeOrg': True,
                                                         'canBePrivate': True, 'canInvite': True},
                                               'shortLink': 'rAWuxf08', 'subscribed': False,
                                               'labelNames': {'green': '', 'yellow': '', 'orange': '', 'red': '',
                                                              'purple': '', 'blue': 'gui', 'sky': 'bot',
                                                              'lime': 'announcememts', 'pink': 'android',
                                                              'black': 'iOS', 'green_dark': 'frontent',
                                                              'yellow_dark': '', 'orange_dark': '', 'red_dark': 'error',
                                                              'purple_dark': '', 'blue_dark': '', 'sky_dark': '',
                                                              'lime_dark': '', 'pink_dark': '', 'black_dark': '',
                                                              'green_light': 'backend', 'yellow_light': '',
                                                              'orange_light': '', 'red_light': '', 'purple_light': '',
                                                              'blue_light': '', 'sky_light': '', 'lime_light': '',
                                                              'pink_light': '', 'black_light': ''}, 'powerUps': [],
                                               'dateLastActivity': '2023-03-13T11:42:40.230Z',
                                               'dateLastView': '2023-03-13T19:45:02.733Z',
                                               'shortUrl': 'https://trello.com/b/rAWuxf08', 'idTags': [],
                                               'datePluginDisable': None, 'creationMethod': 'automatic',
                                               'ixUpdate': '729', 'templateGallery': None, 'enterpriseOwned': False,
                                               'idBoardSource': None,
                                               'premiumFeatures': ['additionalBoardBackgrounds', 'additionalStickers',
                                                                   'customBoardBackgrounds', 'customEmoji',
                                                                   'customStickers', 'plugins'],
                                               'idMemberCreator': '63e9d509205aef8fd7069794', 'memberships': [
        {'idMember': '63e9d509205aef8fd7069794', 'memberType': 'admin', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea22a4dd3aa382a077fbaa'},
        {'idMember': '63ea2270d626f4ccafa6ff6b', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea22df359fa4e94aa40ae2'},
        {'idMember': '626566d47279b31f29f1121f', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea22e1b64b232b58a2fb25'},
        {'idMember': '63e389bbd86539e63e742e92', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea22e56ab7721d33796db4'},
        {'idMember': '63e37c6518095d6965e88428', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea22ea128c070feaae6cc5'},
        {'idMember': '63ea22281627e1830b03f4cf', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea22ea924da00eb0ca0da2'},
        {'idMember': '63ea225dc56d8690c50485f0', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea22eb0f9909c7440de1a1'},
        {'idMember': '63ea22372edd1230dbc83c07', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea22ee7aaa01a6d131abe8'},
        {'idMember': '63ea22629c9669c3c0f0a83f', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea230db7a00ad3d4671cb3'},
        {'idMember': '63ea227728ee0b875a66f2f5', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea23122c2a3ddcb9234cbc'},
        {'idMember': '63ea22aa9d3776a08fb32bc4', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea232bbe1522d0bd1d7c4e'},
        {'idMember': '63ea22f4ffbd3c26f2523e84', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea2335087f5a2e1c4b3736'},
        {'idMember': '63ea2252ec8a5141c9ba640b', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea23410246fb79f5513270'},
        {'idMember': '63ea22cf2803a40c1aec0ff6', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea235a72c335923a7f585e'},
        {'idMember': '63ea226cab04b3d79fb6049e', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea236aad3a7db5b42d6882'},
        {'idMember': '63ea241c656766291b405b56', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ea241e8a9f70bd81bd8cca'},
        {'idMember': '63eca904fec862fc5de5d891', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63eca90675d9eefcca8f9f51'},
        {'idMember': '63ee0da8181dba69698dafac', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '63ee0daa83cdc7ab3ac506b0'},
        {'idMember': '640f08452d638e6fd01cd000', 'memberType': 'normal', 'unconfirmed': False, 'deactivated': False,
         'id': '640f0be12a1dfd3cd754351a'}]}, {'id': '6408e6892c1b72773399d993',
                                               'nodeId': 'ari:cloud:trello::board/workspace/63ea2305039a525e80a5a455/6408e6892c1b72773399d993',
                                               'name': 'yangi', 'desc': '', 'descData': None, 'closed': False,
                                               'dateClosed': None, 'idOrganization': '63ea2305039a525e80a5a455',
                                               'idEnterprise': None, 'limits': {
        'attachments': {'perBoard': {'status': 'ok', 'disableAt': 36000, 'warnAt': 28800},
                        'perCard': {'status': 'ok', 'disableAt': 1000, 'warnAt': 800}},
        'boards': {'totalMembersPerBoard': {'status': 'ok', 'disableAt': 1600, 'warnAt': 1280},
                   'totalAccessRequestsPerBoard': {'status': 'ok', 'disableAt': 4000, 'warnAt': 3200}},
        'cards': {'openPerBoard': {'status': 'ok', 'disableAt': 5000, 'warnAt': 4000},
                  'openPerList': {'status': 'ok', 'disableAt': 5000, 'warnAt': 4000},
                  'totalPerBoard': {'status': 'ok', 'disableAt': 2000000, 'warnAt': 1600000},
                  'totalPerList': {'status': 'ok', 'disableAt': 1000000, 'warnAt': 800000}},
        'checklists': {'perBoard': {'status': 'ok', 'disableAt': 1800000, 'warnAt': 1440000},
                       'perCard': {'status': 'ok', 'disableAt': 500, 'warnAt': 400}},
        'checkItems': {'perChecklist': {'status': 'ok', 'disableAt': 200, 'warnAt': 160}},
        'customFields': {'perBoard': {'status': 'ok', 'disableAt': 50, 'warnAt': 40}},
        'customFieldOptions': {'perField': {'status': 'ok', 'disableAt': 50, 'warnAt': 40}},
        'labels': {'perBoard': {'status': 'ok', 'disableAt': 1000, 'warnAt': 800}},
        'lists': {'openPerBoard': {'status': 'ok', 'disableAt': 500, 'warnAt': 400},
                  'totalPerBoard': {'status': 'ok', 'disableAt': 3000, 'warnAt': 2400}},
        'stickers': {'perCard': {'status': 'ok', 'disableAt': 70, 'warnAt': 56}},
        'reactions': {'perAction': {'status': 'ok', 'disableAt': 900, 'warnAt': 720},
                      'uniquePerAction': {'status': 'ok', 'disableAt': 17, 'warnAt': 14}}}, 'pinned': False,
                                               'starred': False, 'url': 'https://trello.com/b/9rHW0lPa/yangi',
                                               'prefs': {'permissionLevel': 'org', 'hideVotes': False,
                                                         'voting': 'disabled', 'comments': 'members',
                                                         'invitations': 'members', 'selfJoin': True, 'cardCovers': True,
                                                         'isTemplate': False, 'cardAging': 'regular',
                                                         'calendarFeedEnabled': False, 'hiddenPluginBoardButtons': [],
                                                         'switcherViews': [{'viewType': 'Board', 'enabled': True,
                                                                            '_id': '6408e6892c1b72773399d994',
                                                                            'typeName': 'SwitcherViews',
                                                                            'id': '6408e6892c1b72773399d994'},
                                                                           {'viewType': 'Table', 'enabled': True,
                                                                            '_id': '6408e6892c1b72773399d995',
                                                                            'typeName': 'SwitcherViews',
                                                                            'id': '6408e6892c1b72773399d995'},
                                                                           {'viewType': 'Calendar', 'enabled': False,
                                                                            '_id': '6408e6892c1b72773399d996',
                                                                            'typeName': 'SwitcherViews',
                                                                            'id': '6408e6892c1b72773399d996'},
                                                                           {'viewType': 'Dashboard', 'enabled': False,
                                                                            '_id': '6408e6892c1b72773399d997',
                                                                            'typeName': 'SwitcherViews',
                                                                            'id': '6408e6892c1b72773399d997'},
                                                                           {'viewType': 'Timeline', 'enabled': False,
                                                                            '_id': '6408e6892c1b72773399d998',
                                                                            'typeName': 'SwitcherViews',
                                                                            'id': '6408e6892c1b72773399d998'},
                                                                           {'viewType': 'Map', 'enabled': False,
                                                                            '_id': '6408e6892c1b72773399d999',
                                                                            'typeName': 'SwitcherViews',
                                                                            'id': '6408e6892c1b72773399d999'}],
                                                         'background': '6408d63b0f806b8ee4869ce9',
                                                         'backgroundColor': None,
                                                         'backgroundImage': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/original/ff57eee00d69318d7befb6cb057fdc45/photo-1677647598949-6b6689bd53f6',
                                                         'backgroundImageScaled': [{'width': 140, 'height': 88,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/140x88/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 256, 'height': 160,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/256x160/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 480, 'height': 300,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/480x300/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 960, 'height': 601,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/960x601/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 1024, 'height': 641,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1024x641/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 1280, 'height': 801,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1280x801/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 1920, 'height': 1202,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/1920x1202/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 2048, 'height': 1282,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/2048x1282/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 2557, 'height': 1600,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/2557x1600/cd0b2f03cbd35c19311c0dbbd0d58212/photo-1677647598949-6b6689bd53f6.jpg'},
                                                                                   {'width': 2560, 'height': 1602,
                                                                                    'url': 'https://trello-backgrounds.s3.amazonaws.com/SharedBackground/original/ff57eee00d69318d7befb6cb057fdc45/photo-1677647598949-6b6689bd53f6'}],
                                                         'backgroundTile': False, 'backgroundBrightness': 'dark',
                                                         'backgroundBottomColor': '#0e161f',
                                                         'backgroundTopColor': '#24292c', 'canBePublic': True,
                                                         'canBeEnterprise': True, 'canBeOrg': True,
                                                         'canBePrivate': True, 'canInvite': True},
                                               'shortLink': '9rHW0lPa', 'subscribed': False,
                                               'labelNames': {'green': '', 'yellow': '', 'orange': '', 'red': '',
                                                              'purple': '', 'blue': '', 'sky': '', 'lime': '',
                                                              'pink': '', 'black': '', 'green_dark': '',
                                                              'yellow_dark': '', 'orange_dark': '', 'red_dark': '',
                                                              'purple_dark': '', 'blue_dark': '', 'sky_dark': '',
                                                              'lime_dark': '', 'pink_dark': '', 'black_dark': '',
                                                              'green_light': '', 'yellow_light': '', 'orange_light': '',
                                                              'red_light': '', 'purple_light': '', 'blue_light': '',
                                                              'sky_light': '', 'lime_light': '', 'pink_light': '',
                                                              'black_light': ''}, 'powerUps': [],
                                               'dateLastActivity': None, 'dateLastView': '2023-03-09T22:44:42.961Z',
                                               'shortUrl': 'https://trello.com/b/9rHW0lPa', 'idTags': [],
                                               'datePluginDisable': None, 'creationMethod': None, 'ixUpdate': '3',
                                               'templateGallery': None, 'enterpriseOwned': False, 'idBoardSource': None,
                                               'premiumFeatures': ['additionalBoardBackgrounds', 'additionalStickers',
                                                                   'customBoardBackgrounds', 'customEmoji',
                                                                   'customStickers', 'plugins'],
                                               'idMemberCreator': '63ea227728ee0b875a66f2f5', 'memberships': [
        {'idMember': '63ea227728ee0b875a66f2f5', 'memberType': 'admin', 'unconfirmed': False, 'deactivated': False,
         'id': '6408e6892c1b72773399d99d'}]}]

